### ISSUE TITLE
 how can I show the Modal by JavaScript Function rather than Link Tag

### ISSUE THREAD

**Issue by myalsailamy** [michaelperrin/bootstrap-modal-sheet#1]
Hi 
thank you for the wonderful tool ,  I have a small question , And I hope you answer it .

The question is how can I show the Modal by JavaScript Function rather than the following code:

    <a data-toggle="sheet" data-sheet-parent="#info-box" href="#mySheet"> Show info </a>

To Become  Something Like this  : 

    function showModalSheet() {
        // Code the SheetModal AS SheetModal Not like BootStrap Modal
    }

*michaelperrin: edited your post to display code blocks*

**Comment by michaelperrin** [comment]
Hi @myalsailamy, thanks for your message.

There is a way to show the modal sheet programmatically:

    function showModalSheet() {
        $('#mySheet').sheet('show');
    }

However, I noticed there is a bug as the modal is not placed at the right position.
I will make a fix by the end of the week.

**Comment by myalsailamy** [comment]
Thanks for help
And I hope you did not forget, I still waiting for you

**Comment by michaelperrin** [comment]
@myalsailamy It will be done during next week for sure!

**Comment by michaelperrin** [comment]
@myalsailamy The bug is now fixed. Usage is described here: https://github.com/michaelperrin/bootstrap-modal-sheet#methods

Please note that the `data-sheet-parent` attribute has to be set on the sheet element it self (in your case the element with `id="info-box"`), and not on the link itself.
